// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: envelope.proto

#include "envelope.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace envelope_proto {
PROTOBUF_CONSTEXPR Envelope::Envelope(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.seq_num_)*/uint64_t{0u}
  , /*decltype(_impl_.payload_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_._oneof_case_)*/{}} {}
struct EnvelopeDefaultTypeInternal {
  PROTOBUF_CONSTEXPR EnvelopeDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~EnvelopeDefaultTypeInternal() {}
  union {
    Envelope _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 EnvelopeDefaultTypeInternal _Envelope_default_instance_;
}  // namespace envelope_proto
static ::_pb::Metadata file_level_metadata_envelope_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_envelope_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_envelope_2eproto = nullptr;

const uint32_t TableStruct_envelope_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::envelope_proto::Envelope, _internal_metadata_),
  ~0u,  // no _extensions_
  PROTOBUF_FIELD_OFFSET(::envelope_proto::Envelope, _impl_._oneof_case_[0]),
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::envelope_proto::Envelope, _impl_.seq_num_),
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  PROTOBUF_FIELD_OFFSET(::envelope_proto::Envelope, _impl_.payload_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::envelope_proto::Envelope)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::envelope_proto::_Envelope_default_instance_._instance,
};

const char descriptor_table_protodef_envelope_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\016envelope.proto\022\016envelope_proto\032\rmatche"
  "r.proto\032\toms.proto\"r\n\010Envelope\022\017\n\007seq_nu"
  "m\030\001 \001(\004\022(\n\007matcher\030\002 \001(\0132\025.matcher_proto"
  ".ActionH\000\022 \n\003oms\030\003 \001(\0132\021.oms_proto.Actio"
  "nH\000B\t\n\007payloadb\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_envelope_2eproto_deps[2] = {
  &::descriptor_table_matcher_2eproto,
  &::descriptor_table_oms_2eproto,
};
static ::_pbi::once_flag descriptor_table_envelope_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_envelope_2eproto = {
    false, false, 182, descriptor_table_protodef_envelope_2eproto,
    "envelope.proto",
    &descriptor_table_envelope_2eproto_once, descriptor_table_envelope_2eproto_deps, 2, 1,
    schemas, file_default_instances, TableStruct_envelope_2eproto::offsets,
    file_level_metadata_envelope_2eproto, file_level_enum_descriptors_envelope_2eproto,
    file_level_service_descriptors_envelope_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_envelope_2eproto_getter() {
  return &descriptor_table_envelope_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_envelope_2eproto(&descriptor_table_envelope_2eproto);
namespace envelope_proto {

// ===================================================================

class Envelope::_Internal {
 public:
  static const ::matcher_proto::Action& matcher(const Envelope* msg);
  static const ::oms_proto::Action& oms(const Envelope* msg);
};

const ::matcher_proto::Action&
Envelope::_Internal::matcher(const Envelope* msg) {
  return *msg->_impl_.payload_.matcher_;
}
const ::oms_proto::Action&
Envelope::_Internal::oms(const Envelope* msg) {
  return *msg->_impl_.payload_.oms_;
}
void Envelope::set_allocated_matcher(::matcher_proto::Action* matcher) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_payload();
  if (matcher) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(matcher));
    if (message_arena != submessage_arena) {
      matcher = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, matcher, submessage_arena);
    }
    set_has_matcher();
    _impl_.payload_.matcher_ = matcher;
  }
  // @@protoc_insertion_point(field_set_allocated:envelope_proto.Envelope.matcher)
}
void Envelope::clear_matcher() {
  if (_internal_has_matcher()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.payload_.matcher_;
    }
    clear_has_payload();
  }
}
void Envelope::set_allocated_oms(::oms_proto::Action* oms) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_payload();
  if (oms) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(oms));
    if (message_arena != submessage_arena) {
      oms = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, oms, submessage_arena);
    }
    set_has_oms();
    _impl_.payload_.oms_ = oms;
  }
  // @@protoc_insertion_point(field_set_allocated:envelope_proto.Envelope.oms)
}
void Envelope::clear_oms() {
  if (_internal_has_oms()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.payload_.oms_;
    }
    clear_has_payload();
  }
}
Envelope::Envelope(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:envelope_proto.Envelope)
}
Envelope::Envelope(const Envelope& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Envelope* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.seq_num_){}
    , decltype(_impl_.payload_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , /*decltype(_impl_._oneof_case_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.seq_num_ = from._impl_.seq_num_;
  clear_has_payload();
  switch (from.payload_case()) {
    case kMatcher: {
      _this->_internal_mutable_matcher()->::matcher_proto::Action::MergeFrom(
          from._internal_matcher());
      break;
    }
    case kOms: {
      _this->_internal_mutable_oms()->::oms_proto::Action::MergeFrom(
          from._internal_oms());
      break;
    }
    case PAYLOAD_NOT_SET: {
      break;
    }
  }
  // @@protoc_insertion_point(copy_constructor:envelope_proto.Envelope)
}

inline void Envelope::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.seq_num_){uint64_t{0u}}
    , decltype(_impl_.payload_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , /*decltype(_impl_._oneof_case_)*/{}
  };
  clear_has_payload();
}

Envelope::~Envelope() {
  // @@protoc_insertion_point(destructor:envelope_proto.Envelope)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Envelope::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (has_payload()) {
    clear_payload();
  }
}

void Envelope::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Envelope::clear_payload() {
// @@protoc_insertion_point(one_of_clear_start:envelope_proto.Envelope)
  switch (payload_case()) {
    case kMatcher: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.payload_.matcher_;
      }
      break;
    }
    case kOms: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.payload_.oms_;
      }
      break;
    }
    case PAYLOAD_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = PAYLOAD_NOT_SET;
}


void Envelope::Clear() {
// @@protoc_insertion_point(message_clear_start:envelope_proto.Envelope)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.seq_num_ = uint64_t{0u};
  clear_payload();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Envelope::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint64 seq_num = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.seq_num_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .matcher_proto.Action matcher = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_matcher(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .oms_proto.Action oms = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr = ctx->ParseMessage(_internal_mutable_oms(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Envelope::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:envelope_proto.Envelope)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 seq_num = 1;
  if (this->_internal_seq_num() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(1, this->_internal_seq_num(), target);
  }

  // .matcher_proto.Action matcher = 2;
  if (_internal_has_matcher()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, _Internal::matcher(this),
        _Internal::matcher(this).GetCachedSize(), target, stream);
  }

  // .oms_proto.Action oms = 3;
  if (_internal_has_oms()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(3, _Internal::oms(this),
        _Internal::oms(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:envelope_proto.Envelope)
  return target;
}

size_t Envelope::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:envelope_proto.Envelope)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint64 seq_num = 1;
  if (this->_internal_seq_num() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_seq_num());
  }

  switch (payload_case()) {
    // .matcher_proto.Action matcher = 2;
    case kMatcher: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.payload_.matcher_);
      break;
    }
    // .oms_proto.Action oms = 3;
    case kOms: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.payload_.oms_);
      break;
    }
    case PAYLOAD_NOT_SET: {
      break;
    }
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Envelope::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Envelope::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Envelope::GetClassData() const { return &_class_data_; }


void Envelope::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Envelope*>(&to_msg);
  auto& from = static_cast<const Envelope&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:envelope_proto.Envelope)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_seq_num() != 0) {
    _this->_internal_set_seq_num(from._internal_seq_num());
  }
  switch (from.payload_case()) {
    case kMatcher: {
      _this->_internal_mutable_matcher()->::matcher_proto::Action::MergeFrom(
          from._internal_matcher());
      break;
    }
    case kOms: {
      _this->_internal_mutable_oms()->::oms_proto::Action::MergeFrom(
          from._internal_oms());
      break;
    }
    case PAYLOAD_NOT_SET: {
      break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Envelope::CopyFrom(const Envelope& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:envelope_proto.Envelope)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Envelope::IsInitialized() const {
  return true;
}

void Envelope::InternalSwap(Envelope* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.seq_num_, other->_impl_.seq_num_);
  swap(_impl_.payload_, other->_impl_.payload_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

::PROTOBUF_NAMESPACE_ID::Metadata Envelope::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_envelope_2eproto_getter, &descriptor_table_envelope_2eproto_once,
      file_level_metadata_envelope_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace envelope_proto
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::envelope_proto::Envelope*
Arena::CreateMaybeMessage< ::envelope_proto::Envelope >(Arena* arena) {
  return Arena::CreateMessageInternal< ::envelope_proto::Envelope >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
