// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: matcher.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_matcher_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_matcher_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_bases.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "types.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_matcher_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_matcher_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_matcher_2eproto;
namespace matcher_proto {
class Action;
struct ActionDefaultTypeInternal;
extern ActionDefaultTypeInternal _Action_default_instance_;
class Book;
struct BookDefaultTypeInternal;
extern BookDefaultTypeInternal _Book_default_instance_;
class CreateBook;
struct CreateBookDefaultTypeInternal;
extern CreateBookDefaultTypeInternal _CreateBook_default_instance_;
class CreateOrder;
struct CreateOrderDefaultTypeInternal;
extern CreateOrderDefaultTypeInternal _CreateOrder_default_instance_;
class Envelope;
struct EnvelopeDefaultTypeInternal;
extern EnvelopeDefaultTypeInternal _Envelope_default_instance_;
class Order;
struct OrderDefaultTypeInternal;
extern OrderDefaultTypeInternal _Order_default_instance_;
class Snapshot;
struct SnapshotDefaultTypeInternal;
extern SnapshotDefaultTypeInternal _Snapshot_default_instance_;
}  // namespace matcher_proto
PROTOBUF_NAMESPACE_OPEN
template<> ::matcher_proto::Action* Arena::CreateMaybeMessage<::matcher_proto::Action>(Arena*);
template<> ::matcher_proto::Book* Arena::CreateMaybeMessage<::matcher_proto::Book>(Arena*);
template<> ::matcher_proto::CreateBook* Arena::CreateMaybeMessage<::matcher_proto::CreateBook>(Arena*);
template<> ::matcher_proto::CreateOrder* Arena::CreateMaybeMessage<::matcher_proto::CreateOrder>(Arena*);
template<> ::matcher_proto::Envelope* Arena::CreateMaybeMessage<::matcher_proto::Envelope>(Arena*);
template<> ::matcher_proto::Order* Arena::CreateMaybeMessage<::matcher_proto::Order>(Arena*);
template<> ::matcher_proto::Snapshot* Arena::CreateMaybeMessage<::matcher_proto::Snapshot>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace matcher_proto {

// ===================================================================

class Book final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:matcher_proto.Book) */ {
 public:
  inline Book() : Book(nullptr) {}
  ~Book() override;
  explicit PROTOBUF_CONSTEXPR Book(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Book(const Book& from);
  Book(Book&& from) noexcept
    : Book() {
    *this = ::std::move(from);
  }

  inline Book& operator=(const Book& from) {
    CopyFrom(from);
    return *this;
  }
  inline Book& operator=(Book&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Book& default_instance() {
    return *internal_default_instance();
  }
  static inline const Book* internal_default_instance() {
    return reinterpret_cast<const Book*>(
               &_Book_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Book& a, Book& b) {
    a.Swap(&b);
  }
  inline void Swap(Book* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Book* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Book* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Book>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Book& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Book& from) {
    Book::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Book* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "matcher_proto.Book";
  }
  protected:
  explicit Book(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kIdFieldNumber = 1,
  };
  // uint64 id = 1;
  void clear_id();
  uint64_t id() const;
  void set_id(uint64_t value);
  private:
  uint64_t _internal_id() const;
  void _internal_set_id(uint64_t value);
  public:

  // @@protoc_insertion_point(class_scope:matcher_proto.Book)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint64_t id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_matcher_2eproto;
};
// -------------------------------------------------------------------

class Order final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:matcher_proto.Order) */ {
 public:
  inline Order() : Order(nullptr) {}
  ~Order() override;
  explicit PROTOBUF_CONSTEXPR Order(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Order(const Order& from);
  Order(Order&& from) noexcept
    : Order() {
    *this = ::std::move(from);
  }

  inline Order& operator=(const Order& from) {
    CopyFrom(from);
    return *this;
  }
  inline Order& operator=(Order&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Order& default_instance() {
    return *internal_default_instance();
  }
  static inline const Order* internal_default_instance() {
    return reinterpret_cast<const Order*>(
               &_Order_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(Order& a, Order& b) {
    a.Swap(&b);
  }
  inline void Swap(Order* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Order* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Order* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Order>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Order& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Order& from) {
    Order::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Order* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "matcher_proto.Order";
  }
  protected:
  explicit Order(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kIdFieldNumber = 1,
    kPriceFieldNumber = 2,
    kQuantityFieldNumber = 3,
    kSideFieldNumber = 4,
  };
  // uint64 id = 1;
  void clear_id();
  uint64_t id() const;
  void set_id(uint64_t value);
  private:
  uint64_t _internal_id() const;
  void _internal_set_id(uint64_t value);
  public:

  // uint64 price = 2;
  void clear_price();
  uint64_t price() const;
  void set_price(uint64_t value);
  private:
  uint64_t _internal_price() const;
  void _internal_set_price(uint64_t value);
  public:

  // uint64 quantity = 3;
  void clear_quantity();
  uint64_t quantity() const;
  void set_quantity(uint64_t value);
  private:
  uint64_t _internal_quantity() const;
  void _internal_set_quantity(uint64_t value);
  public:

  // .types_proto.Side side = 4;
  void clear_side();
  ::types_proto::Side side() const;
  void set_side(::types_proto::Side value);
  private:
  ::types_proto::Side _internal_side() const;
  void _internal_set_side(::types_proto::Side value);
  public:

  // @@protoc_insertion_point(class_scope:matcher_proto.Order)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint64_t id_;
    uint64_t price_;
    uint64_t quantity_;
    int side_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_matcher_2eproto;
};
// -------------------------------------------------------------------

class CreateBook final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:matcher_proto.CreateBook) */ {
 public:
  inline CreateBook() : CreateBook(nullptr) {}
  ~CreateBook() override;
  explicit PROTOBUF_CONSTEXPR CreateBook(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  CreateBook(const CreateBook& from);
  CreateBook(CreateBook&& from) noexcept
    : CreateBook() {
    *this = ::std::move(from);
  }

  inline CreateBook& operator=(const CreateBook& from) {
    CopyFrom(from);
    return *this;
  }
  inline CreateBook& operator=(CreateBook&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CreateBook& default_instance() {
    return *internal_default_instance();
  }
  static inline const CreateBook* internal_default_instance() {
    return reinterpret_cast<const CreateBook*>(
               &_CreateBook_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(CreateBook& a, CreateBook& b) {
    a.Swap(&b);
  }
  inline void Swap(CreateBook* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CreateBook* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CreateBook* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<CreateBook>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const CreateBook& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const CreateBook& from) {
    CreateBook::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CreateBook* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "matcher_proto.CreateBook";
  }
  protected:
  explicit CreateBook(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kBookFieldNumber = 1,
  };
  // .matcher_proto.Book book = 1;
  bool has_book() const;
  private:
  bool _internal_has_book() const;
  public:
  void clear_book();
  const ::matcher_proto::Book& book() const;
  PROTOBUF_NODISCARD ::matcher_proto::Book* release_book();
  ::matcher_proto::Book* mutable_book();
  void set_allocated_book(::matcher_proto::Book* book);
  private:
  const ::matcher_proto::Book& _internal_book() const;
  ::matcher_proto::Book* _internal_mutable_book();
  public:
  void unsafe_arena_set_allocated_book(
      ::matcher_proto::Book* book);
  ::matcher_proto::Book* unsafe_arena_release_book();

  // @@protoc_insertion_point(class_scope:matcher_proto.CreateBook)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::matcher_proto::Book* book_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_matcher_2eproto;
};
// -------------------------------------------------------------------

class CreateOrder final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:matcher_proto.CreateOrder) */ {
 public:
  inline CreateOrder() : CreateOrder(nullptr) {}
  ~CreateOrder() override;
  explicit PROTOBUF_CONSTEXPR CreateOrder(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  CreateOrder(const CreateOrder& from);
  CreateOrder(CreateOrder&& from) noexcept
    : CreateOrder() {
    *this = ::std::move(from);
  }

  inline CreateOrder& operator=(const CreateOrder& from) {
    CopyFrom(from);
    return *this;
  }
  inline CreateOrder& operator=(CreateOrder&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CreateOrder& default_instance() {
    return *internal_default_instance();
  }
  static inline const CreateOrder* internal_default_instance() {
    return reinterpret_cast<const CreateOrder*>(
               &_CreateOrder_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(CreateOrder& a, CreateOrder& b) {
    a.Swap(&b);
  }
  inline void Swap(CreateOrder* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CreateOrder* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CreateOrder* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<CreateOrder>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const CreateOrder& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const CreateOrder& from) {
    CreateOrder::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CreateOrder* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "matcher_proto.CreateOrder";
  }
  protected:
  explicit CreateOrder(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kOrderFieldNumber = 2,
    kBookIdFieldNumber = 1,
  };
  // .matcher_proto.Order order = 2;
  bool has_order() const;
  private:
  bool _internal_has_order() const;
  public:
  void clear_order();
  const ::matcher_proto::Order& order() const;
  PROTOBUF_NODISCARD ::matcher_proto::Order* release_order();
  ::matcher_proto::Order* mutable_order();
  void set_allocated_order(::matcher_proto::Order* order);
  private:
  const ::matcher_proto::Order& _internal_order() const;
  ::matcher_proto::Order* _internal_mutable_order();
  public:
  void unsafe_arena_set_allocated_order(
      ::matcher_proto::Order* order);
  ::matcher_proto::Order* unsafe_arena_release_order();

  // uint64 book_id = 1;
  void clear_book_id();
  uint64_t book_id() const;
  void set_book_id(uint64_t value);
  private:
  uint64_t _internal_book_id() const;
  void _internal_set_book_id(uint64_t value);
  public:

  // @@protoc_insertion_point(class_scope:matcher_proto.CreateOrder)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::matcher_proto::Order* order_;
    uint64_t book_id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_matcher_2eproto;
};
// -------------------------------------------------------------------

class Snapshot final :
    public ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase /* @@protoc_insertion_point(class_definition:matcher_proto.Snapshot) */ {
 public:
  inline Snapshot() : Snapshot(nullptr) {}
  explicit PROTOBUF_CONSTEXPR Snapshot(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Snapshot(const Snapshot& from);
  Snapshot(Snapshot&& from) noexcept
    : Snapshot() {
    *this = ::std::move(from);
  }

  inline Snapshot& operator=(const Snapshot& from) {
    CopyFrom(from);
    return *this;
  }
  inline Snapshot& operator=(Snapshot&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Snapshot& default_instance() {
    return *internal_default_instance();
  }
  static inline const Snapshot* internal_default_instance() {
    return reinterpret_cast<const Snapshot*>(
               &_Snapshot_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(Snapshot& a, Snapshot& b) {
    a.Swap(&b);
  }
  inline void Swap(Snapshot* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Snapshot* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Snapshot* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Snapshot>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyFrom;
  inline void CopyFrom(const Snapshot& from) {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl(*this, from);
  }
  using ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeFrom;
  void MergeFrom(const Snapshot& from) {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl(*this, from);
  }
  public:

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "matcher_proto.Snapshot";
  }
  protected:
  explicit Snapshot(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:matcher_proto.Snapshot)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
  };
  friend struct ::TableStruct_matcher_2eproto;
};
// -------------------------------------------------------------------

class Action final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:matcher_proto.Action) */ {
 public:
  inline Action() : Action(nullptr) {}
  ~Action() override;
  explicit PROTOBUF_CONSTEXPR Action(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Action(const Action& from);
  Action(Action&& from) noexcept
    : Action() {
    *this = ::std::move(from);
  }

  inline Action& operator=(const Action& from) {
    CopyFrom(from);
    return *this;
  }
  inline Action& operator=(Action&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Action& default_instance() {
    return *internal_default_instance();
  }
  enum ActionCase {
    kCreateBook = 1,
    kCreateOrder = 2,
    kSnapshot = 3,
    ACTION_NOT_SET = 0,
  };

  static inline const Action* internal_default_instance() {
    return reinterpret_cast<const Action*>(
               &_Action_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(Action& a, Action& b) {
    a.Swap(&b);
  }
  inline void Swap(Action* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Action* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Action* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Action>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Action& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Action& from) {
    Action::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Action* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "matcher_proto.Action";
  }
  protected:
  explicit Action(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kCreateBookFieldNumber = 1,
    kCreateOrderFieldNumber = 2,
    kSnapshotFieldNumber = 3,
  };
  // .matcher_proto.CreateBook create_book = 1;
  bool has_create_book() const;
  private:
  bool _internal_has_create_book() const;
  public:
  void clear_create_book();
  const ::matcher_proto::CreateBook& create_book() const;
  PROTOBUF_NODISCARD ::matcher_proto::CreateBook* release_create_book();
  ::matcher_proto::CreateBook* mutable_create_book();
  void set_allocated_create_book(::matcher_proto::CreateBook* create_book);
  private:
  const ::matcher_proto::CreateBook& _internal_create_book() const;
  ::matcher_proto::CreateBook* _internal_mutable_create_book();
  public:
  void unsafe_arena_set_allocated_create_book(
      ::matcher_proto::CreateBook* create_book);
  ::matcher_proto::CreateBook* unsafe_arena_release_create_book();

  // .matcher_proto.CreateOrder create_order = 2;
  bool has_create_order() const;
  private:
  bool _internal_has_create_order() const;
  public:
  void clear_create_order();
  const ::matcher_proto::CreateOrder& create_order() const;
  PROTOBUF_NODISCARD ::matcher_proto::CreateOrder* release_create_order();
  ::matcher_proto::CreateOrder* mutable_create_order();
  void set_allocated_create_order(::matcher_proto::CreateOrder* create_order);
  private:
  const ::matcher_proto::CreateOrder& _internal_create_order() const;
  ::matcher_proto::CreateOrder* _internal_mutable_create_order();
  public:
  void unsafe_arena_set_allocated_create_order(
      ::matcher_proto::CreateOrder* create_order);
  ::matcher_proto::CreateOrder* unsafe_arena_release_create_order();

  // .matcher_proto.Snapshot snapshot = 3;
  bool has_snapshot() const;
  private:
  bool _internal_has_snapshot() const;
  public:
  void clear_snapshot();
  const ::matcher_proto::Snapshot& snapshot() const;
  PROTOBUF_NODISCARD ::matcher_proto::Snapshot* release_snapshot();
  ::matcher_proto::Snapshot* mutable_snapshot();
  void set_allocated_snapshot(::matcher_proto::Snapshot* snapshot);
  private:
  const ::matcher_proto::Snapshot& _internal_snapshot() const;
  ::matcher_proto::Snapshot* _internal_mutable_snapshot();
  public:
  void unsafe_arena_set_allocated_snapshot(
      ::matcher_proto::Snapshot* snapshot);
  ::matcher_proto::Snapshot* unsafe_arena_release_snapshot();

  void clear_action();
  ActionCase action_case() const;
  // @@protoc_insertion_point(class_scope:matcher_proto.Action)
 private:
  class _Internal;
  void set_has_create_book();
  void set_has_create_order();
  void set_has_snapshot();

  inline bool has_action() const;
  inline void clear_has_action();

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    union ActionUnion {
      constexpr ActionUnion() : _constinit_{} {}
        ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized _constinit_;
      ::matcher_proto::CreateBook* create_book_;
      ::matcher_proto::CreateOrder* create_order_;
      ::matcher_proto::Snapshot* snapshot_;
    } action_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    uint32_t _oneof_case_[1];

  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_matcher_2eproto;
};
// -------------------------------------------------------------------

class Envelope final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:matcher_proto.Envelope) */ {
 public:
  inline Envelope() : Envelope(nullptr) {}
  ~Envelope() override;
  explicit PROTOBUF_CONSTEXPR Envelope(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Envelope(const Envelope& from);
  Envelope(Envelope&& from) noexcept
    : Envelope() {
    *this = ::std::move(from);
  }

  inline Envelope& operator=(const Envelope& from) {
    CopyFrom(from);
    return *this;
  }
  inline Envelope& operator=(Envelope&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Envelope& default_instance() {
    return *internal_default_instance();
  }
  enum PayloadCase {
    kAction = 2,
    PAYLOAD_NOT_SET = 0,
  };

  static inline const Envelope* internal_default_instance() {
    return reinterpret_cast<const Envelope*>(
               &_Envelope_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  friend void swap(Envelope& a, Envelope& b) {
    a.Swap(&b);
  }
  inline void Swap(Envelope* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Envelope* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Envelope* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Envelope>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Envelope& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Envelope& from) {
    Envelope::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Envelope* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "matcher_proto.Envelope";
  }
  protected:
  explicit Envelope(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSeqNumFieldNumber = 1,
    kActionFieldNumber = 2,
  };
  // uint64 seq_num = 1;
  void clear_seq_num();
  uint64_t seq_num() const;
  void set_seq_num(uint64_t value);
  private:
  uint64_t _internal_seq_num() const;
  void _internal_set_seq_num(uint64_t value);
  public:

  // .matcher_proto.Action action = 2;
  bool has_action() const;
  private:
  bool _internal_has_action() const;
  public:
  void clear_action();
  const ::matcher_proto::Action& action() const;
  PROTOBUF_NODISCARD ::matcher_proto::Action* release_action();
  ::matcher_proto::Action* mutable_action();
  void set_allocated_action(::matcher_proto::Action* action);
  private:
  const ::matcher_proto::Action& _internal_action() const;
  ::matcher_proto::Action* _internal_mutable_action();
  public:
  void unsafe_arena_set_allocated_action(
      ::matcher_proto::Action* action);
  ::matcher_proto::Action* unsafe_arena_release_action();

  void clear_payload();
  PayloadCase payload_case() const;
  // @@protoc_insertion_point(class_scope:matcher_proto.Envelope)
 private:
  class _Internal;
  void set_has_action();

  inline bool has_payload() const;
  inline void clear_has_payload();

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint64_t seq_num_;
    union PayloadUnion {
      constexpr PayloadUnion() : _constinit_{} {}
        ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized _constinit_;
      ::matcher_proto::Action* action_;
    } payload_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    uint32_t _oneof_case_[1];

  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_matcher_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Book

// uint64 id = 1;
inline void Book::clear_id() {
  _impl_.id_ = uint64_t{0u};
}
inline uint64_t Book::_internal_id() const {
  return _impl_.id_;
}
inline uint64_t Book::id() const {
  // @@protoc_insertion_point(field_get:matcher_proto.Book.id)
  return _internal_id();
}
inline void Book::_internal_set_id(uint64_t value) {
  
  _impl_.id_ = value;
}
inline void Book::set_id(uint64_t value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:matcher_proto.Book.id)
}

// -------------------------------------------------------------------

// Order

// uint64 id = 1;
inline void Order::clear_id() {
  _impl_.id_ = uint64_t{0u};
}
inline uint64_t Order::_internal_id() const {
  return _impl_.id_;
}
inline uint64_t Order::id() const {
  // @@protoc_insertion_point(field_get:matcher_proto.Order.id)
  return _internal_id();
}
inline void Order::_internal_set_id(uint64_t value) {
  
  _impl_.id_ = value;
}
inline void Order::set_id(uint64_t value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:matcher_proto.Order.id)
}

// uint64 price = 2;
inline void Order::clear_price() {
  _impl_.price_ = uint64_t{0u};
}
inline uint64_t Order::_internal_price() const {
  return _impl_.price_;
}
inline uint64_t Order::price() const {
  // @@protoc_insertion_point(field_get:matcher_proto.Order.price)
  return _internal_price();
}
inline void Order::_internal_set_price(uint64_t value) {
  
  _impl_.price_ = value;
}
inline void Order::set_price(uint64_t value) {
  _internal_set_price(value);
  // @@protoc_insertion_point(field_set:matcher_proto.Order.price)
}

// uint64 quantity = 3;
inline void Order::clear_quantity() {
  _impl_.quantity_ = uint64_t{0u};
}
inline uint64_t Order::_internal_quantity() const {
  return _impl_.quantity_;
}
inline uint64_t Order::quantity() const {
  // @@protoc_insertion_point(field_get:matcher_proto.Order.quantity)
  return _internal_quantity();
}
inline void Order::_internal_set_quantity(uint64_t value) {
  
  _impl_.quantity_ = value;
}
inline void Order::set_quantity(uint64_t value) {
  _internal_set_quantity(value);
  // @@protoc_insertion_point(field_set:matcher_proto.Order.quantity)
}

// .types_proto.Side side = 4;
inline void Order::clear_side() {
  _impl_.side_ = 0;
}
inline ::types_proto::Side Order::_internal_side() const {
  return static_cast< ::types_proto::Side >(_impl_.side_);
}
inline ::types_proto::Side Order::side() const {
  // @@protoc_insertion_point(field_get:matcher_proto.Order.side)
  return _internal_side();
}
inline void Order::_internal_set_side(::types_proto::Side value) {
  
  _impl_.side_ = value;
}
inline void Order::set_side(::types_proto::Side value) {
  _internal_set_side(value);
  // @@protoc_insertion_point(field_set:matcher_proto.Order.side)
}

// -------------------------------------------------------------------

// CreateBook

// .matcher_proto.Book book = 1;
inline bool CreateBook::_internal_has_book() const {
  return this != internal_default_instance() && _impl_.book_ != nullptr;
}
inline bool CreateBook::has_book() const {
  return _internal_has_book();
}
inline void CreateBook::clear_book() {
  if (GetArenaForAllocation() == nullptr && _impl_.book_ != nullptr) {
    delete _impl_.book_;
  }
  _impl_.book_ = nullptr;
}
inline const ::matcher_proto::Book& CreateBook::_internal_book() const {
  const ::matcher_proto::Book* p = _impl_.book_;
  return p != nullptr ? *p : reinterpret_cast<const ::matcher_proto::Book&>(
      ::matcher_proto::_Book_default_instance_);
}
inline const ::matcher_proto::Book& CreateBook::book() const {
  // @@protoc_insertion_point(field_get:matcher_proto.CreateBook.book)
  return _internal_book();
}
inline void CreateBook::unsafe_arena_set_allocated_book(
    ::matcher_proto::Book* book) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.book_);
  }
  _impl_.book_ = book;
  if (book) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:matcher_proto.CreateBook.book)
}
inline ::matcher_proto::Book* CreateBook::release_book() {
  
  ::matcher_proto::Book* temp = _impl_.book_;
  _impl_.book_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::matcher_proto::Book* CreateBook::unsafe_arena_release_book() {
  // @@protoc_insertion_point(field_release:matcher_proto.CreateBook.book)
  
  ::matcher_proto::Book* temp = _impl_.book_;
  _impl_.book_ = nullptr;
  return temp;
}
inline ::matcher_proto::Book* CreateBook::_internal_mutable_book() {
  
  if (_impl_.book_ == nullptr) {
    auto* p = CreateMaybeMessage<::matcher_proto::Book>(GetArenaForAllocation());
    _impl_.book_ = p;
  }
  return _impl_.book_;
}
inline ::matcher_proto::Book* CreateBook::mutable_book() {
  ::matcher_proto::Book* _msg = _internal_mutable_book();
  // @@protoc_insertion_point(field_mutable:matcher_proto.CreateBook.book)
  return _msg;
}
inline void CreateBook::set_allocated_book(::matcher_proto::Book* book) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.book_;
  }
  if (book) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(book);
    if (message_arena != submessage_arena) {
      book = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, book, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.book_ = book;
  // @@protoc_insertion_point(field_set_allocated:matcher_proto.CreateBook.book)
}

// -------------------------------------------------------------------

// CreateOrder

// uint64 book_id = 1;
inline void CreateOrder::clear_book_id() {
  _impl_.book_id_ = uint64_t{0u};
}
inline uint64_t CreateOrder::_internal_book_id() const {
  return _impl_.book_id_;
}
inline uint64_t CreateOrder::book_id() const {
  // @@protoc_insertion_point(field_get:matcher_proto.CreateOrder.book_id)
  return _internal_book_id();
}
inline void CreateOrder::_internal_set_book_id(uint64_t value) {
  
  _impl_.book_id_ = value;
}
inline void CreateOrder::set_book_id(uint64_t value) {
  _internal_set_book_id(value);
  // @@protoc_insertion_point(field_set:matcher_proto.CreateOrder.book_id)
}

// .matcher_proto.Order order = 2;
inline bool CreateOrder::_internal_has_order() const {
  return this != internal_default_instance() && _impl_.order_ != nullptr;
}
inline bool CreateOrder::has_order() const {
  return _internal_has_order();
}
inline void CreateOrder::clear_order() {
  if (GetArenaForAllocation() == nullptr && _impl_.order_ != nullptr) {
    delete _impl_.order_;
  }
  _impl_.order_ = nullptr;
}
inline const ::matcher_proto::Order& CreateOrder::_internal_order() const {
  const ::matcher_proto::Order* p = _impl_.order_;
  return p != nullptr ? *p : reinterpret_cast<const ::matcher_proto::Order&>(
      ::matcher_proto::_Order_default_instance_);
}
inline const ::matcher_proto::Order& CreateOrder::order() const {
  // @@protoc_insertion_point(field_get:matcher_proto.CreateOrder.order)
  return _internal_order();
}
inline void CreateOrder::unsafe_arena_set_allocated_order(
    ::matcher_proto::Order* order) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.order_);
  }
  _impl_.order_ = order;
  if (order) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:matcher_proto.CreateOrder.order)
}
inline ::matcher_proto::Order* CreateOrder::release_order() {
  
  ::matcher_proto::Order* temp = _impl_.order_;
  _impl_.order_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::matcher_proto::Order* CreateOrder::unsafe_arena_release_order() {
  // @@protoc_insertion_point(field_release:matcher_proto.CreateOrder.order)
  
  ::matcher_proto::Order* temp = _impl_.order_;
  _impl_.order_ = nullptr;
  return temp;
}
inline ::matcher_proto::Order* CreateOrder::_internal_mutable_order() {
  
  if (_impl_.order_ == nullptr) {
    auto* p = CreateMaybeMessage<::matcher_proto::Order>(GetArenaForAllocation());
    _impl_.order_ = p;
  }
  return _impl_.order_;
}
inline ::matcher_proto::Order* CreateOrder::mutable_order() {
  ::matcher_proto::Order* _msg = _internal_mutable_order();
  // @@protoc_insertion_point(field_mutable:matcher_proto.CreateOrder.order)
  return _msg;
}
inline void CreateOrder::set_allocated_order(::matcher_proto::Order* order) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.order_;
  }
  if (order) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(order);
    if (message_arena != submessage_arena) {
      order = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, order, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.order_ = order;
  // @@protoc_insertion_point(field_set_allocated:matcher_proto.CreateOrder.order)
}

// -------------------------------------------------------------------

// Snapshot

// -------------------------------------------------------------------

// Action

// .matcher_proto.CreateBook create_book = 1;
inline bool Action::_internal_has_create_book() const {
  return action_case() == kCreateBook;
}
inline bool Action::has_create_book() const {
  return _internal_has_create_book();
}
inline void Action::set_has_create_book() {
  _impl_._oneof_case_[0] = kCreateBook;
}
inline void Action::clear_create_book() {
  if (_internal_has_create_book()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.action_.create_book_;
    }
    clear_has_action();
  }
}
inline ::matcher_proto::CreateBook* Action::release_create_book() {
  // @@protoc_insertion_point(field_release:matcher_proto.Action.create_book)
  if (_internal_has_create_book()) {
    clear_has_action();
    ::matcher_proto::CreateBook* temp = _impl_.action_.create_book_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.action_.create_book_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::matcher_proto::CreateBook& Action::_internal_create_book() const {
  return _internal_has_create_book()
      ? *_impl_.action_.create_book_
      : reinterpret_cast< ::matcher_proto::CreateBook&>(::matcher_proto::_CreateBook_default_instance_);
}
inline const ::matcher_proto::CreateBook& Action::create_book() const {
  // @@protoc_insertion_point(field_get:matcher_proto.Action.create_book)
  return _internal_create_book();
}
inline ::matcher_proto::CreateBook* Action::unsafe_arena_release_create_book() {
  // @@protoc_insertion_point(field_unsafe_arena_release:matcher_proto.Action.create_book)
  if (_internal_has_create_book()) {
    clear_has_action();
    ::matcher_proto::CreateBook* temp = _impl_.action_.create_book_;
    _impl_.action_.create_book_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void Action::unsafe_arena_set_allocated_create_book(::matcher_proto::CreateBook* create_book) {
  clear_action();
  if (create_book) {
    set_has_create_book();
    _impl_.action_.create_book_ = create_book;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:matcher_proto.Action.create_book)
}
inline ::matcher_proto::CreateBook* Action::_internal_mutable_create_book() {
  if (!_internal_has_create_book()) {
    clear_action();
    set_has_create_book();
    _impl_.action_.create_book_ = CreateMaybeMessage< ::matcher_proto::CreateBook >(GetArenaForAllocation());
  }
  return _impl_.action_.create_book_;
}
inline ::matcher_proto::CreateBook* Action::mutable_create_book() {
  ::matcher_proto::CreateBook* _msg = _internal_mutable_create_book();
  // @@protoc_insertion_point(field_mutable:matcher_proto.Action.create_book)
  return _msg;
}

// .matcher_proto.CreateOrder create_order = 2;
inline bool Action::_internal_has_create_order() const {
  return action_case() == kCreateOrder;
}
inline bool Action::has_create_order() const {
  return _internal_has_create_order();
}
inline void Action::set_has_create_order() {
  _impl_._oneof_case_[0] = kCreateOrder;
}
inline void Action::clear_create_order() {
  if (_internal_has_create_order()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.action_.create_order_;
    }
    clear_has_action();
  }
}
inline ::matcher_proto::CreateOrder* Action::release_create_order() {
  // @@protoc_insertion_point(field_release:matcher_proto.Action.create_order)
  if (_internal_has_create_order()) {
    clear_has_action();
    ::matcher_proto::CreateOrder* temp = _impl_.action_.create_order_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.action_.create_order_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::matcher_proto::CreateOrder& Action::_internal_create_order() const {
  return _internal_has_create_order()
      ? *_impl_.action_.create_order_
      : reinterpret_cast< ::matcher_proto::CreateOrder&>(::matcher_proto::_CreateOrder_default_instance_);
}
inline const ::matcher_proto::CreateOrder& Action::create_order() const {
  // @@protoc_insertion_point(field_get:matcher_proto.Action.create_order)
  return _internal_create_order();
}
inline ::matcher_proto::CreateOrder* Action::unsafe_arena_release_create_order() {
  // @@protoc_insertion_point(field_unsafe_arena_release:matcher_proto.Action.create_order)
  if (_internal_has_create_order()) {
    clear_has_action();
    ::matcher_proto::CreateOrder* temp = _impl_.action_.create_order_;
    _impl_.action_.create_order_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void Action::unsafe_arena_set_allocated_create_order(::matcher_proto::CreateOrder* create_order) {
  clear_action();
  if (create_order) {
    set_has_create_order();
    _impl_.action_.create_order_ = create_order;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:matcher_proto.Action.create_order)
}
inline ::matcher_proto::CreateOrder* Action::_internal_mutable_create_order() {
  if (!_internal_has_create_order()) {
    clear_action();
    set_has_create_order();
    _impl_.action_.create_order_ = CreateMaybeMessage< ::matcher_proto::CreateOrder >(GetArenaForAllocation());
  }
  return _impl_.action_.create_order_;
}
inline ::matcher_proto::CreateOrder* Action::mutable_create_order() {
  ::matcher_proto::CreateOrder* _msg = _internal_mutable_create_order();
  // @@protoc_insertion_point(field_mutable:matcher_proto.Action.create_order)
  return _msg;
}

// .matcher_proto.Snapshot snapshot = 3;
inline bool Action::_internal_has_snapshot() const {
  return action_case() == kSnapshot;
}
inline bool Action::has_snapshot() const {
  return _internal_has_snapshot();
}
inline void Action::set_has_snapshot() {
  _impl_._oneof_case_[0] = kSnapshot;
}
inline void Action::clear_snapshot() {
  if (_internal_has_snapshot()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.action_.snapshot_;
    }
    clear_has_action();
  }
}
inline ::matcher_proto::Snapshot* Action::release_snapshot() {
  // @@protoc_insertion_point(field_release:matcher_proto.Action.snapshot)
  if (_internal_has_snapshot()) {
    clear_has_action();
    ::matcher_proto::Snapshot* temp = _impl_.action_.snapshot_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.action_.snapshot_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::matcher_proto::Snapshot& Action::_internal_snapshot() const {
  return _internal_has_snapshot()
      ? *_impl_.action_.snapshot_
      : reinterpret_cast< ::matcher_proto::Snapshot&>(::matcher_proto::_Snapshot_default_instance_);
}
inline const ::matcher_proto::Snapshot& Action::snapshot() const {
  // @@protoc_insertion_point(field_get:matcher_proto.Action.snapshot)
  return _internal_snapshot();
}
inline ::matcher_proto::Snapshot* Action::unsafe_arena_release_snapshot() {
  // @@protoc_insertion_point(field_unsafe_arena_release:matcher_proto.Action.snapshot)
  if (_internal_has_snapshot()) {
    clear_has_action();
    ::matcher_proto::Snapshot* temp = _impl_.action_.snapshot_;
    _impl_.action_.snapshot_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void Action::unsafe_arena_set_allocated_snapshot(::matcher_proto::Snapshot* snapshot) {
  clear_action();
  if (snapshot) {
    set_has_snapshot();
    _impl_.action_.snapshot_ = snapshot;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:matcher_proto.Action.snapshot)
}
inline ::matcher_proto::Snapshot* Action::_internal_mutable_snapshot() {
  if (!_internal_has_snapshot()) {
    clear_action();
    set_has_snapshot();
    _impl_.action_.snapshot_ = CreateMaybeMessage< ::matcher_proto::Snapshot >(GetArenaForAllocation());
  }
  return _impl_.action_.snapshot_;
}
inline ::matcher_proto::Snapshot* Action::mutable_snapshot() {
  ::matcher_proto::Snapshot* _msg = _internal_mutable_snapshot();
  // @@protoc_insertion_point(field_mutable:matcher_proto.Action.snapshot)
  return _msg;
}

inline bool Action::has_action() const {
  return action_case() != ACTION_NOT_SET;
}
inline void Action::clear_has_action() {
  _impl_._oneof_case_[0] = ACTION_NOT_SET;
}
inline Action::ActionCase Action::action_case() const {
  return Action::ActionCase(_impl_._oneof_case_[0]);
}
// -------------------------------------------------------------------

// Envelope

// uint64 seq_num = 1;
inline void Envelope::clear_seq_num() {
  _impl_.seq_num_ = uint64_t{0u};
}
inline uint64_t Envelope::_internal_seq_num() const {
  return _impl_.seq_num_;
}
inline uint64_t Envelope::seq_num() const {
  // @@protoc_insertion_point(field_get:matcher_proto.Envelope.seq_num)
  return _internal_seq_num();
}
inline void Envelope::_internal_set_seq_num(uint64_t value) {
  
  _impl_.seq_num_ = value;
}
inline void Envelope::set_seq_num(uint64_t value) {
  _internal_set_seq_num(value);
  // @@protoc_insertion_point(field_set:matcher_proto.Envelope.seq_num)
}

// .matcher_proto.Action action = 2;
inline bool Envelope::_internal_has_action() const {
  return payload_case() == kAction;
}
inline bool Envelope::has_action() const {
  return _internal_has_action();
}
inline void Envelope::set_has_action() {
  _impl_._oneof_case_[0] = kAction;
}
inline void Envelope::clear_action() {
  if (_internal_has_action()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.payload_.action_;
    }
    clear_has_payload();
  }
}
inline ::matcher_proto::Action* Envelope::release_action() {
  // @@protoc_insertion_point(field_release:matcher_proto.Envelope.action)
  if (_internal_has_action()) {
    clear_has_payload();
    ::matcher_proto::Action* temp = _impl_.payload_.action_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.payload_.action_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::matcher_proto::Action& Envelope::_internal_action() const {
  return _internal_has_action()
      ? *_impl_.payload_.action_
      : reinterpret_cast< ::matcher_proto::Action&>(::matcher_proto::_Action_default_instance_);
}
inline const ::matcher_proto::Action& Envelope::action() const {
  // @@protoc_insertion_point(field_get:matcher_proto.Envelope.action)
  return _internal_action();
}
inline ::matcher_proto::Action* Envelope::unsafe_arena_release_action() {
  // @@protoc_insertion_point(field_unsafe_arena_release:matcher_proto.Envelope.action)
  if (_internal_has_action()) {
    clear_has_payload();
    ::matcher_proto::Action* temp = _impl_.payload_.action_;
    _impl_.payload_.action_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void Envelope::unsafe_arena_set_allocated_action(::matcher_proto::Action* action) {
  clear_payload();
  if (action) {
    set_has_action();
    _impl_.payload_.action_ = action;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:matcher_proto.Envelope.action)
}
inline ::matcher_proto::Action* Envelope::_internal_mutable_action() {
  if (!_internal_has_action()) {
    clear_payload();
    set_has_action();
    _impl_.payload_.action_ = CreateMaybeMessage< ::matcher_proto::Action >(GetArenaForAllocation());
  }
  return _impl_.payload_.action_;
}
inline ::matcher_proto::Action* Envelope::mutable_action() {
  ::matcher_proto::Action* _msg = _internal_mutable_action();
  // @@protoc_insertion_point(field_mutable:matcher_proto.Envelope.action)
  return _msg;
}

inline bool Envelope::has_payload() const {
  return payload_case() != PAYLOAD_NOT_SET;
}
inline void Envelope::clear_has_payload() {
  _impl_._oneof_case_[0] = PAYLOAD_NOT_SET;
}
inline Envelope::PayloadCase Envelope::payload_case() const {
  return Envelope::PayloadCase(_impl_._oneof_case_[0]);
}
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace matcher_proto

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_matcher_2eproto
